//import cx from 'classnames';
import * as React from 'react';
import { InjectedIntlProps, injectIntl } from 'react-intl';
import { connect } from 'react-redux';
import { RouterProps } from 'react-router';
import { Link, withRouter } from 'react-router-dom';
//import { SignInComponent, TwoFactorAuth } from '../../components';
import {setDocumentTitle } from '../../helpers';
import {
    RootState,
	labelFetch,
	selectCurrentColorTheme,
} from '../../modules';

interface ReduxProps {
    colorTheme: string;
}

type Props = ReduxProps & RouterProps & InjectedIntlProps;

class Privacy extends React.Component<Props> {
    public componentDidMount() {
        setDocumentTitle('Privacy & Conditions');
    }

    public componentWillReceiveProps(props: Props) {
        
    }

    public render() {
        //const { loading } = this.props;

        //const className = cx('pg-privacy-screen__container', { loading });
        return (
            <div className="pg-privacy-screen">
			
			    <div className="wrapper">
					   <h2>{this.translate('privacy.heading-top')}</h2>
					   <div className="css-1vgmakj">
						  <div className="calibre" id="calibre_link-0">
							 <br /> <i><b>Last Updated: May 11, 2020</b></i> <br /><br /> 
							 <p className="block_2"><span >These Terms of Use are the legal binding agreement between </span><b  className="calibre1">BME Technologies OÜ</b><span >, a legal person incorporated under the laws of Estonia with a </span><b  className="calibre1">registry code 14710805</b><span > with a registered address at </span><b  className="calibre1">Harju maakond, Tallinn, Lasnamäe linnaosa, Peterburi tee 47</b><span >, 11415, its subsidiaries and affiliated parties (the '</span><b  className="calibre1">Company</b><span >”) and the users of the website coinmudra.com.com (the '</span><b  className="calibre1">Site</b><span >'). By using this Site, and further by registering to use our Service, you (the '</span><b  className="calibre1">Member</b><span >', '</span><b  className="calibre1">You</b><span >', '</span><b  className="calibre1">Your</b><span >' or '</span><b  className="calibre1">Yourself</b><span >') accept and comply with the terms and conditions governing Your use of the Company’s’ website (the “</span><b  className="calibre1">Site</b><span >”) and the services offered therein (the '</span><b  className="calibre1">Terms of Use</b><span >'). You should read the entire Terms of Use carefully before You use the Site or any of the services offered on the Site (the '</span><b  className="calibre1">Services</b><span >').</span></p>
							 <p className="block_2" >BY USING THE SITE OR OTHERWISE ACCESSING OR USING THE SERVICES, YOU AGREE TO THE TERMS OF USE. IF YOU DO NOT ACCEPT THE TERMS OF USE OR ANY PROVISION THEREIN, DO NOT ACCESS THE SITE OR USE THE SERVICES.</p>
							 <p className="block_3"><span  className="text_">The Services allow buyers and sellers to buy and sell victual currencies (which are commodities developed on distributed ledger technology applications, such as blockchain, and include Bitcoin, Ethereum, Bitcoin Cash and others, herein the '</span><span  className="text_1">Virtual Currency</span><span  className="text_">”) through the Site on global international markets, all subject to these Terms of Use, the </span><a  href="/privacy" className="text_2">Privacy Policy</a><span  className="text_"> and the </span><a  href="https://coinmudra.com.com/kyc_policy" className="text_2">AML/KYC Policy</a><span  className="text_">, which are an integral part of these Terms of Use.</span></p>
							 <p className="block_4"><span  className="text_3">For more information about Bitcoin, see </span><span className="text_4"></span><a target="https://bitcoin.org" href="https://bitcoin.org" className="calibre2"><span  className="text_4"></span><span className="text_4"></span><span  className="text_5">https://bitcoin.org</span></a><span  className="text_3">.</span></p>
							 <p className="block_4"><span  className="text_3">For more information about Ethereum, see </span><span className="text_4"></span><a target="https://ethereum.org" href="https://ethereum.org" className="calibre2"><span  className="text_4"></span><span className="text_4"></span><span  className="text_5">https://ethereum.org</span></a><span  className="text_3">.</span></p>
							 <p className="block_2" >Depending on Your country of residence, You may not be eligible to use all or some of the Services of the Site. As the regulations are constantly changing the Company may withdraw or amend your Member access to the Site without any notice and based on its sole discretion, all in order to comply with the prevailing laws and regulations.&nbsp;</p>
							 <p className="block_2" >Notwithstanding the above, it is Your responsibility to follow laws and regulations of Your country of residence and/or country from which You access this Site and Services.&nbsp;</p>
							 <p className="block_2"><span >By opening an account to use the Services (the '</span><b  className="calibre1">Account</b><span >'), You expressly represent and warrant that:</span></p>
							 <ol className="list_">
								<li className="block_5"><span >You have accepted these Terms of Use;&nbsp;</span></li>
								<li className="block_5"><span >You are at least 18 years of age and have the full legal capacity to accept these Terms of Use and are of legal age to form a binding contract under law applicable to You, including to enter into a transaction involving Virtual Currency (for physical person);</span></li>
								<li className="block_5"><span >You are a legally established organization (for legal entities);</span></li>
								<li className="block_5"><span >You have the capacity to enter into a legally binding contract and use the Site, and are not prohibited to do so and use the Services by the Applicable Law or any other laws that may apply;</span></li>
								<li className="block_5"><span >You have not previously been removed from using the Services;</span></li>
								<li className="block_5"><span >You do not currently have another Account on the Site, </span><span  className="text_6">unless opening another account is explicitly permitted</span><span >;</span></li>
								<li className="block_5"><span >You have all necessary rights and authority to bind a legal entity with these Terms of Use in an event you are entering into these Terms of Use on behalf of such legal entity, of which you are a director, officer, employee, or agent;</span></li>
								<li className="block_5"><span >By accessing this Site and using the Services You are not breaching the laws and regulations of Your country of residence/ country of Your citizenship. Should any laws change, You undertake that You will immediately cease the use of the Services.&nbsp;<br className="calibre3" />&nbsp;</span></li>
							 </ol>
							 <p className="block_6" >Risks Warning&nbsp;</p>
							 <p className="block_2"><b  className="calibre1">Financial Risks.&nbsp;</b><span >The trading of goods and products, real or virtual, as well as Virtual Currencies involves significant risks. Prices can fluctuate on any given day. Due to such price fluctuations, You may increase or lose value in Your assets at any given moment. Any assets, digital or not, may be subject to large shifts in value and may even become worthless. There is an inherent risk that losses will occur as a result of buying, selling or trading anything on a market.</span></p>
							 <p className="block_2" >You should carefully assess whether Your financial standing and tolerance for risk are suitable for buying / selling of Virtual Currencies.</p>
							 <p className="block_2" >THE COMPANY DOES NOT AND CANNOT GUARANTEE ANY PROFIT FROM BUYING OR SELLING OF VIRTUAL CURRENCIES OR ANY OTHER ACTIVITY ASSOCIATED WITH THE SITE. YOU MUST CAREFULLY CONSIDER IF HOLDING VIRTUAL CURRENCIES IS SUITABLE FOR YOU DEPENDING ON YOUR FINANCIAL CIRCUMSTANCES.</p>
							 <p className="block_2"><b  className="calibre1">Operational and Cybersecurity Risks.</b><span >&nbsp;Hackers or other malicious groups or organizations may attempt to interfere with Your Virtual Currencies in a variety of ways. You are solely responsible to keep your Virtual Currencies and your Account secure. Do not share login and password to your Account with other persons.</span></p>
							 <p className="block_2" >THE COMPANY DOES NOT AND CANNOT GUARANTEE SECURITY OF YOUR VIRTUAL CURRENCIES.&nbsp;</p>
							 <p className="block_2"><b  className="calibre1">Regulatory Risks.&nbsp;</b><span >The regulatory status of Virtual Currencies and distributed ledger technology is unclear or unsettled in many jurisdictions. It is difficult to predict how or whether regulatory agencies may apply existing regulation with respect to such technology and its applications. It is likewise difficult to predict how or whether legislatures or regulatory agencies may implement changes to law and regulation affecting distributed ledger technology and its applications, including the Company. Regulatory actions could negatively impact Virtual Currencies in various ways.&nbsp;</span></p>
							 <p ><span className="block_7">The Company cannot guarantee the security of you Virtual Currencies, however, in the event of any security breaches with your Virtual Currencies, the Company intends to make every feasible effort to mitigate damages from such security breaches.</span></p>
							 <p className="block_2"><b  className="calibre1">OTHER.&nbsp;</b><span >VIRTUAL CURRENCIES ARE A NEW TECHNOLOGY. IN ADDITION TO THE RISKS INCLUDED ABOVE, THERE ARE OTHER RISKS ASSOCIATED WITH YOUR PURCHASE, HOLDING AND USE OF VIRTUAL CURRENCIES, INCLUDING THOSE THAT THE COMPANY CANNOT ANTICIPATE. SUCH RISKS MAY FURTHER MATERIALIZE AS UNANTICIPATED VARIATIONS OR COMBINATIONS OF THE RISKS DISCUSSED ABOVE. YOU MUST CAREFULLY CONSIDER IF BUYING OR SELLING VIRTUAL CURRENCIES IS SUITABLE FOR YOU DEPENDING ON YOUR CIRCUMSTANCES.<br className="calibre3" /></span></p>
							 
							 <p className="block_6" >Rules for Maintaining Your Account</p>
							 <p className="block_2" >The Site is for Your own personal and non-commercial use only. The Company is vigilant in maintaining the security of the Site and the Services. By registering with us, You agree to provide us with current, accurate, and complete information about You as prompted by the registration process and the verification process, and to keep such information updated at all times. You further agree that You will not use any Account other than for Your own, or access the Account of any other Member at any time, or assist others in obtaining unauthorized access.</p>
							 <p className="block_2" >The creation or use of the Account without obtaining our prior express permission will result in the immediate suspension of all said Accounts, as well as all pending buy/sell offers. Any attempt to do so or to assist others (Members or otherwise), or the distribution of instructions, software or tools for that purpose, will result in the Accounts of such Members being terminated, without derogating from any other remedy to which the Company may be entitled for such a violation and the Company may take further actions against You.</p>
							 <p className="block_4"><span  className="text_3">You may only open </span><span  className="text_7">more than</span><span  className="text_3"> one Account </span><span  className="text_7">on conditions, specifically mentioned on the </span><span className="text_4"></span><a href="mailto:support@koinmudra.com" className="calibre2"><span  className="text_4"></span><span className="text_4"></span><span  className="text_8">Site</span></a><span  className="text_3">. You are responsible for maintaining the confidentiality of Your Account information, including Your password, safeguarding Your own Virtual Currencies, and for all activity and Transactions that are posted to Your Account. The Company may request additional information as necessary, including in the event of any suspicious activity related to Your Account, including authenticating documents, and may freeze any Transactions pending our review. You are obligated to comply with these security requests, or accept termination of Your Account.</span></p>
							 <p className="block_4"><span  className="text_3">You are required to notify us immediately of any unauthorized use of Your Account or password, or any other breach of security by email addressed to&nbsp;</span><span className="text_4"></span><a href="mailto:support@koinmudra.com" className="calibre2"><span  className="text_4"></span><span className="text_4"></span><span  className="text_5">support@coinmudra.com.com</span></a><span  className="text_3">.&nbsp;</span></p>
							 <p className="block_2"><span >You agree to receive transactional emails </span><span  className="text_6">about deposits, withdrawals and other critical Site functionality</span><span >, from us. Such emails will be cancelled upon Your request using the 'unsubscribe' option presented in any such email.&nbsp;</span></p>
							 <p className="block_2" >You warrant not to use methods to conceal the location from which you access the Site and that You will disclose to the Company Your accurate and true location.</p>
							 <p className="block_2" >You agree and undertake that You will not use the Service to perform illegal activity of any sort.&nbsp;</p>
							 <p className="block_2" >Any Member who violates these Terms of Use will have their Account terminated immediately, and thereafter will be held liable for losses incurred by the Company or any other Member.&nbsp;<br className="calibre3" />&nbsp;</p>
							 <p className="block_6" >Account Establishment</p>
							 <p className="block_2" >Use of the Site and the Services is subject to completing the initial registration process by providing accurate information and documentation, including without limitations, Your name, e-mail address, password, and affirming Your acceptance of these Terms of Use. The aforementioned notwithstanding, the Company may, in its sole discretion, deny You the option to establish the Account, or limit the Accounts that any person may establish and maintain at any time.</p>
							 <p className="block_4"><span  className="text_3">You acknowledge that in addition to the above, certain features of the Services require that You provide the Company with certain information and documents and undergo a verification procedure. For more information, please, read the AML/KYC Policy, that is available at </span><span className="text_4"></span><a href="https://coinmudra.com.com/kyc_policy" className="calibre2"><span  className="text_4"></span><span className="text_4"></span><span  className="text_9">https://coinmudra.com.com/kyc_policy</span></a><span  className="text_3">. </span></p>
							 <p className="block_2" >You warrant that any and all of the personal information submitted as may be required, is accurate and authentic. Furthermore, You warrant to update the Company with respect to any changes in or of the information submitted to the Company. The Company may use or transfer Your information to third party service providers for the purpose of providing You with the Services under the Site or the improvement thereof.&nbsp;</p>
							 <p className="block_2" >You acknowledge that the Company performs inquiries to verify Your personal information, whether directly or through the assistance of third-party service providers in its attempt to prevent misidentification, fraud, suspicious activity or money laundering or any other forbidden activity and may take actions with respect to the outcome of such inquiries as it deems necessary. You hereby provide the Company with Your authorization for such inquiries as aforementioned, including with respect to a query of Your account information.<br className="calibre3" />&nbsp;</p>
							 <p className="block_6" >Provisions of the Services</p>
							 <p className="block_2"><b  className="calibre1">License.&nbsp;</b><span >The Company grants You with a limited, non-transferable, non-exclusive license to access and use the Site, the Services, the Company’s marks, trademarks, designs, and any related content, data and information provided therein (the '</span><b  className="calibre1">Site Content</b><span >') subject to the Terms of Use and exclusively for Your personal use as permitted by the Company and as may be further amended by the Company from time to time. You warrant not to, directly or indirectly, copy, modify, create derivative works, reverse engineer, disassemble, distribute, sell or license any of the Site Content or any part therein to any third party.</span></p>
							 <p className="block_2" >The Company cannot and does not guarantee the availability of the Services at all times. You acknowledge that in order to protect the Site and its operation, the Company reserves the right at all times, to delay or deny any transaction if it perceives a risk of misconduct, fraud or illegal activity, subject to the Company’s sole discretion.</p>
							 <p className="block_2" >All components, Site Content, and the Site as a whole belong to the Company and are protected with, including, but not limited to copyright, trademarks, trade secrets. All rights reserved. Violation of any of the intellectual property rights of the Company is strictly prohibited.</p>
							 <p className="block_4"><span  className="text_10">Transactions Limits.&nbsp;</span><span  className="text_3">You acknowledge that certain limits may apply to the Transaction volume in any given period in accordance with the Company’s policies as may be amended from time to time. For more information please visit </span><span className="text_4"></span><a href="https://kb.coinmudra.com.com/coinmudra.com" className="calibre2"><span  className="text_4"></span><span className="text_4"></span><span  className="text_9">https://kb.coinmudra.com.com/coinmudra.com</span></a><span  className="text_3">. </span></p>
							 <p className="block_2"><b  className="calibre1">REFUNDS.&nbsp;</b><span >DUE TO THE NATURE OF THE SERVICES THE SITE PROVIDES, ALL PURCHASES MADE ON THE SITE ARE NON-REFUNDABLE. You acknowledge that transactions executed are non-cancellable and You cannot change or reverse any Transaction which was completed or which is pending.</span></p>
							 <p className="block_2" >The Company may refund a fully or partially unmatched with another Member offer to a Transaction to sale/purchase Virtual Currency if offer to a Transaction or its part remains unmatched for a substantial period of time or if poses threats to the Company's or the Site’s cyber and/or technical security (e.g. when multiple small offers to sale/purchase Virtual Currency are created).</p>
							 <p className="block_2"><b  className="calibre1">Erroneous Transactions.&nbsp;</b><span >The Company shall have the right to reverse any Transaction that was made in error due to technology malfunctioning or malicious interference with the Site. </span></p>
							 <p className="block_2"><b  className="calibre1">Payment Declined.&nbsp;</b><span >The Company may terminate any Transaction for payment that was declined for any reason. If possible, in the event of termination of any Transaction, the Company will provide You with notification to that regard.</span></p>
							 <p className="block_2"><b  className="calibre1">Privacy of Members Information.&nbsp;</b><span >Provided that in the course of using the Services You are disclosed of any Member’s information, You are obligated to keep such Member’s information in strict confidence and use it in connection with the Services only. You may not disclose such Member’s information without the said Member’s prior written consent.</span></p>
							 <p className="block_4"><span  className="text_10">Login Information Security.&nbsp;</span><span  className="text_3">Your login information and password must be kept in strict confidence at all times. Compromising Your login information may expose Your Account to unauthorized access by third-parties which may result in loss or theft of Virtual Currencies or funds from Your Account, including linked accounts, such as Your linked bank accounts and credit cards. In order to receive security alerts from the Company, You must update the Company with respect to changes in Your email address and telephone number. At no event will the Company be held responsible for any damages or losses which You may sustain as a result of compromise of Your Account login credentials due to no fault of the Company and/or failure to follow or act on any notices or alerts that we may send to You. Any suspected compromise of Your login information should be immediately reported to the Company at&nbsp;</span><span className="text_4"></span><a href="mailto:support@coinmudra.com.com" className="calibre2"><span  className="text_4"></span><span className="text_4"></span><span  className="text_5">support@coinmudra.com.com</span></a><span  className="text_3">.</span></p>
							 <p className="block_2"><b  className="calibre1">Site Content Accuracy.&nbsp;</b><span >You acknowledge that the Site and any content therein, may contain errors from time to time and may not be accurate or current at all time. In addition, the Site may suffer technical errors. Without derogating from the abovementioned, the Company takes reasonable measures to provide You with accurate information as possible, information may be changed or updated from time to time without notice, including without limitation information regarding our policies, products and Services.</span></p>
							 <p className="block_2" >You should verify all information before relying on it, and all decisions based on information contained on the Company Site are Your sole responsibility and the Company shall have no liability for such decisions.</p>
							 <p className="block_2" >The Site may include links to third party materials which may be provided as a convenience but are not endorsed by the Company. You acknowledge and agree that the Company is not responsible for the content or services promoted by any third party or on any third-party sites accessible through or linked to the Company Site.</p>
							 <p className="block_2"><b  className="calibre1">Third Party Access. </b><span >The Account is for Your own personal use. You should not let any other person use Your Account. In addition, You will hold the Company harmless and will indemnify and defend the Company from any liability arising out of or related to any act or omission of any third party with access to Your Account.</span></p>
							 <p className="block_2"><b  className="calibre1">Prohibited Acts.&nbsp;</b><span >The License granted to You for the use of the Services on the Site is subject to Your obligation not to engage in any prohibited activity. You acknowledge that the Company reserves the right to review, monitor, record and/or disclose any information as may be necessary to comply with any applicable laws, regulations, legal process or governmental request. Should the Company determine, in its sole discretion, that the activity on Your Account is suspicious or related to any prohibited activity or illegitimate operation, the Company may cancel or suspend Your Account, block any outstanding Transactions and deny any new Transactions and freeze any funds available on Yours Account.&nbsp;</span></p>
							 <p className="block_2"><b  className="calibre1">Security and Viruses.&nbsp;</b><span >Any use of the Internet may be subject to virus attack and communication failure. The Company shall not bear any liability, whatsoever, for any damage or interruptions caused by computer viruses, spyware, Trojan horses, worms or other malware that may affect Your systems, computer or other equipment, or any phishing, spoofing or other virus attacks. The Company recommends that all Members use a reputable and available virus screening and prevention software at all times. You should also apply caution when reviewing text messages and emails purporting to originate from the Company as SMS and emails are also vulnerable to phishing and spoofing and additional viruses. It is advisable that You log into Your Account through the Site only and avoid using unauthentic communication advising You options to log in.</span></p>
							 <p className="block_8">&nbsp;</p>
							 <p className="block_6" >Member Conduct</p>
							 <p className="block_2" >While visiting, accessing, using the Site and Services, you agree to:</p>
							 <p className="block_2" >1) not violate or assist any third party in violating these Terms of Use and/or any Applicable Law, which may include but is not limited to international laws, national laws, statutes, regulations, etc.;</p>
							 <p className="block_2" >2) not provide false, inaccurate, incomplete and misleading information to the Company;</p>
							 <p className="block_2" >3) not violate intellectual property rights (trademark, copyright, patent, and other intellectual property rights) of the Company;</p>
							 <p className="block_2" >4) not use the Site in any way that can damage, disable or overburden the Site, which may include but is not limited to uploading or in any other way, while using the Website, sending viruses, Trojan horses, spyware, adware or any other malicious code; performing DDoS attacks, interfering with or disrupting any network, equipment, or server connected to or used to provide services on the Site;</p>
							 <p className="block_2" >5) not attempt to gain unauthorized access to the Site, other Member’s Accounts, computer systems or networks connected to the Site or to extract data from the Site;</p>
							 <p className="block_2" >6) not share your Account and/or password with third parties or use any other Member's Account and/or password;</p>
							 <p className="block_2" >7) not impersonate or misrepresent your affiliation with another Member, person or entity, nor make other fraudulent, false, deceptive, or misleading representations;</p>
							 <p className="block_2" >8) not violate any laws that apply in your jurisdiction concerning the use of Virtual Currencies;</p>
							 <p className="block_2" >9) not violate these Terms of Use and the Applicable Law in any other way;</p>
							 <p className="block_2" >10) not engage in any market manipulation, including but not limited to pump and dump schemes, wash trading, self-trading, front running, quote stuffing, and spoofing, or layering regardless of whether prohibited by any law and the Applicable Law;</p>
							 <p className="block_2" >11) to notify the Company immediately if you become aware of any unauthorized use of your Account and password by any person or any other violations to the security rules;</p>
							 <p className="block_2" >12) to notify the Company immediately if you become aware of any violations to the security rules;</p>
							 <p className="block_2" >13) to strictly observe the security, authentication, deposit, order, withdrawal mechanisms and procedures on the Site;</p>
							 <p className="block_2" >14) to log out from the Site by taking proper steps at the end of every visit;</p>
							 <p className="block_2" >15) to warrant you are aware of the risks in using the and have the necessary experience and knowledge to understand the risks involved in relation to Services provided by the Company. These risks include the high volatility risk of Virtual Currencies, and that you may lose all of the funds in your trading account if the market moves against you;</p>
							 <p className="block_2" >16) to acknowledge and agree that the Services should only be used by you if you:</p>
							 <p className="block_2" >a) have knowledge and experience in highly volatile markets; and</p>
							 <p className="block_2" >b) have a high risk tolerance;</p>
							 <p className="block_2" >17) to only provide withdrawal addressed that are your own and that you have full control over this address and check withdrawal information before making a withdrawal.</p>
							 <p className="block_8">&nbsp;</p>
							 <p className="block_6" >Use of Account Services</p>
							 <p className="block_2"><span >The Services offered to Members with verified Accounts include purchasing and selling through the Site, as applicable, and keeping of Virtual Currencies in Your eWallet on the Site until withdrawal is made (each transaction is hereinafter referred to as '</span><b  className="calibre1">Transaction</b><span >').</span></p>
							 <p className="block_2" >The Company reserves the right to deny processing any pending Transaction if required to do so by law, regulations, competent court order or other competent authority or in the event any Virtual Currency Transaction is in violation of any provision of these Terms of Use or puts the Company’s operation, good name or reputation at risk. In addition, the Company may take any additional actions as available to it under any laws or regulations and these Terms of Use with respect to such Transaction.</p>
							 <p className="block_2" >You acknowledge that the Company will not be liable for any error with respect to Your instructions as provided.</p>
							 <p className="block_2" >All Transactions are pending confirmation process. Pending Transactions are considered not completed Transactions and may remain unconfirmed for the duration necessary for the confirmation of such Transaction.<br className="calibre3" />&nbsp;</p>
							 <p className="block_6" >Member’s Content</p>
							 <p className="block_2" >Should You upload any content on the Site, including without limitations, any text, photo, or other material, You warrant that such content will not consist of: (a) false, misleading information or misappropriation; (b) copyrighted material which You are not authorized to post publicly; or (c) obscene, offensive, profane, unlawful content or any content which, subject to the Company’s sole discretion, may harm or risk the Company’s good name and reputation.</p>
							 <p className="block_2" >Without relieving You of Your responsibility as abovementioned, the Company may, subject to Company’s sole discretion, remove any content which is in violation of the above detailed in addition to any further action which the Company deems necessary.</p>
							 <p className="block_2" >You acknowledge that the Company cannot and does not endorse or guarantee the authenticity, identity or reliability of any content and information posted by any Member of the Site, thus relying on Members’ content is solely at Your own discretion and risk.<br className="calibre3" />&nbsp;</p>
							 <p className="block_6" >Payment Service Providers</p>
							 <p className="block_2" >You acknowledge that the Company may, subject to the Company’s sole discretion, use third-party payment processing service providers to process any local currency payment between You and the Company, including but not limited to payments in relation to Your use of the Services and any Transaction executed by You. In such cases, You confirm that the Company will provide certain information and/or documentation about You, including with respect to a Transaction executed by You as needed to complete the Transaction or as required under any inquiry or in the event of detection of fraud or suspicion of such.<br className="calibre3" />&nbsp;</p>
							 <p className="block_6" >The Price</p>
							 <p className="block_2"><span >The price as displayed on the Site, will be applicable to each Transaction You execute using the Services (the '</span><b  className="calibre1">Price</b><span >'). The applicable Price will be displayed prior to completing each Transaction. The Company reserves the right to adjust its Prices at any time as appearing on each Transaction.</span></p>
							 <p className="block_4"><span  className="text_3">The Prices are at all times available at the </span><span className="text_4"></span><a href="https://kb.coinmudra.com.com/fees-structure" className="calibre2"><span  className="text_4"></span><span className="text_4"></span><span  className="text_9">Fee Structure</span></a><span  className="text_3">, which are the integral part of these Terms of Use.</span></p>
							 <p className="block_2" >Depending on Your jurisdiction, You may be eligible to buy or sell the Virtual Currencies through the Site subject to the rate assigned to any given transaction. The Price quoted on the Site for each Transaction may be dependent on the Services You choose to use.</p>
							 <p className="block_2" >You agree and confirm that due to price volatility of the Virtual Currencies the Price may change before the purchase and/or sale is executed.&nbsp;<br className="calibre3" />&nbsp;</p>
							 <p className="block_6" >Purchasing Virtual Currencies</p>
							 <p className="block_2" >Following successful establishment of Your Account, including certain verification process as required by the Company, You may begin purchasing Virtual Currencies on a per Transaction basis. Before doing so, you have to deposit Virtual Currency or fiat money to your Account by following deposit instructions on your Account page. You should not attempt to deposit any assets on the if your Account has been closed, suspended, or deleted.</p>
							 <p className="block_2" >The Company cannot guarantee that all payment methods will be available to You. The availability of each payment method depends on a number of factors, including but not limited to Your location, the identification information You have provided the Company, and certain limitations imposed by third party payment processors.</p>
							 <p className="block_2" >You can withdraw Virtual Currency or fiat money at any time at your sole discretion. You can withdraw your Virtual Currency or fiat money in any amount, provided there are enough Virtual Currency or fiat money on your Account to support your current and pending Transactions, including their Price. The Company will use reasonable efforts to deliver the purchased Virtual Currencies to You at the earliest possibility following the withdrawal request. </p>
							 <p className="block_2" >The Company shall not be liable for the transfer of Virtual Currency or fiat money to other wallets and addresses. You are solely liable for the accuracy of blockchain information / banking information, required for carrying out a withdrawal. The Company advises to always check the accuracy of information provided for withdrawal purposes.</p>
							 <p className="block_2" >However, You acknowledge that delivery of the Virtual Currencies purchased by You may be completed separately from the actual debit from Your payment method, and may take time for the Virtual Currencies transfer to be processed. You also acknowledge that in certain occasions, the Company may not be able to fulfil Your purchase request.</p>
							 <p className="block_2" >Using the purchasing Services on the Company’s Site does not provide You with a guarantee that You will be able to sell the purchased Virtual Currencies through the Site or to any third party at a later time and at no event will the Company be obligated to purchase from You any Virtual Currencies.&nbsp;</p>
							 <p className="block_8">&nbsp;</p>
							 <p className="block_6" >Sell Transactions</p>
							 <p className="block_2" >The Company may provide You with the option to sell Your Virtual Currencies through the Site subject to Company’s sole discretion, which shall not be deemed as the Company’s obligation to purchase any Virtual Currencies from You.&nbsp;</p>
							 <p className="block_2" >Such option, if provided by the Company, is subject to successfully establishing Your Account, including certain verification process as required by the Company, and by providing Your valid payment method to the Company.</p>
							 <p className="block_2" >Receipt of funds will depend on the payment type You have provided, and may take a certain amount of business days subject to third party providers.<br className="calibre3" />&nbsp;</p>
							 <p className="block_6" >Compliance</p>
							 <p className="block_2" >Your use of the Service must be in compliance with all laws, regulations, anti-money laundering provisions and KYC regulations applicable to You based on Your applicable jurisdiction. It is Your exclusive responsibility to ensure that Your use of the Site and the Services is compliant with the laws and regulations that are applicable to You.</p>
							 <p className="block_2"><b  className="calibre1">Applicable Sanctions.&nbsp;</b><span >You warrant that You will comply with all applicable international economic and export sanctions and any requirement therein.&nbsp;</span></p>
							 <p className="block_2" >Without limiting the generality of the aforementioned, You will not use the Services available on the Site if any of the following applies to You:</p>
							 <ul className="list_1">
								<li className="block_9"><span  className="text_3">You are a citizen, resident, incorporate in the Country, the Company does not work with, as described in the </span><span className="text_4"></span><a href="https://coinmudra.com.com/kyc_policy" className="calibre2"><span  className="text_4"></span><span className="text_4"></span><span  className="text_9">AML/KYC Policy</span></a><span  className="text_3"> (Iran, Syria, Sudan, North Korea, the USA); or</span></li>
								<li className="block_5"><span >Your name appears on any of the lists of sanctioned persons (the '</span><b  className="calibre1">Restricted Persons</b><span >') or You intend to distribute or provide the Services to any person of the Restricted Persons. <br className="calibre3" />&nbsp;</span></li>
							 </ul>
							 <p className="block_6" >Applicable Taxes</p>
							 <p className="block_2" >You are exclusively responsible to inquire with respect to the taxes applicable to Your Transactions on the Site. The Company is not and will at no event be deemed as providing any tax advice or consultation, You must seek your own tax advice in connection with purchasing or selling of any Virtual Currencies. It is Your responsibility to report and remit the taxes payable to the appropriate tax authorities.<br className="calibre3" />&nbsp;</p>
							 <p className="block_6" >Suspension, Termination, and Cancellation</p>
							 <p className="block_2" >You acknowledges that, at any time, the Company, subject to its sole discretion and without any advance notice, will be entitled to terminate Your access to the Site and to Your Account, including without limitation, the Company’s rights to: (a) refuse processing, to cancel or to reverse any Transaction of Virtual Currency, regardless if corresponding funds have been debited from Your payment method; or (b) suspend, restrict, or terminate Your Account; or (c) prohibit access to the Site and its content, tools, delay or remove hosted content and take technical and legal measures to keep Members off the Site due to any reason subject to the Company’s sole discretion, including without limitation as a result of:</p>
							 <p className="block_2" >(i) Violation of these Terms of Use, including without limitations, failure to pay for any Transaction and providing the Company with false, incomplete, misleading, inaccurate information; or </p>
							 <p className="block_2" >(ii) Attempts to gain unauthorized access to the Site or another Member’s account or providing assistance to others’ attempting to do so; or </p>
							 <p className="block_2" >(iii) the Company detected unusual activities or behaviour on your Account, or has reasonable suspicion that a Transaction involves illegal activity, including without limitations, money laundering, terrorist financing, fraud, or any other crime; or </p>
							 <p className="block_2" >(iv) the Company reasonably suspects that Your Account or any Transaction is related to prohibited use or is non-compliant with any applicable laws or regulations; or </p>
							 <p className="block_2" >(v) the Company is requested to do so by a court order, law enforcement or other government or regulatory order or if Your Account is subject to litigation or investigation; or</p>
							 <p className="block_2"><span >(vi) subject to the Company’s discretion, You abuse the Services provided by the Company, including by opening multiple Accounts </span><span  className="text_6">(when opening more than one account is not explicitly permitted)</span><span > and/or taking advantages of promotions in bad faith; or </span></p>
							 <p className="block_2" >(vii) Any of the Company’s third party providers denies providing You the Services; or </p>
							 <p className="block_2" >(viii) if the Company believes such You are creating any possible legal liabilities for the Company; or </p>
							 <p className="block_2" >(ix) force majeure events, including operational and technical errors.</p>
							 <p className="block_2" >The abovementioned notwithstanding, the Company may, subject to its sole discretion terminate the Services or refuse to open any person an account or terminate any use by You of the Site.</p>
							 <p className="block_2" >Upon any suspension, termination or cancellation of a Transaction, the Company is under no obligation to allow You to reinstate such Transaction and may not provide You the same price or same terms as any cancelled Transaction.</p>
							 <p className="block_2" >In the event Your Account is terminated by the Company, the Company may provide You with a notice of immediate termination. In addition, You acknowledge that the Company is not obligated to disclose any findings and information acquired by Company’s security and risk management procedures.</p>
							 <p className="block_3"><span  className="text_11">In the event Your Account is terminated by the Company, assets on your Account shall be transferred to addresses, provided by you to our customer support at </span><Link to="mailto:support@coinmudra.com.com" className="text_12">support@coinmudra.com.com</Link><span  className="text_11">.</span></p>
							 <p className="block_4"><span  className="text_3">Termination by You. You may terminate Your Account at any time by submitting Your request to terminate Your Account at&nbsp;</span><span className="text_4"></span><a href="mailto:support@coinmudra.com.com" className="calibre2"><span  className="text_4"></span><span className="text_4"></span><span  className="text_5">support@coinmudra.com.com</span></a><span  className="text_3">. No termination fee shall apply, except that You will be responsible for fulfilling any outstanding payment obligations to the Company existing as of the effective date of termination and to settle any pending Transactions. The Company reserves the right to suspend any pending transactions at the time of cancellation.</span></p>
							 <p className="block_2" >The Company retains information for as long as we have a business or tax need or as required under applicable laws, regulations and/or government orders from time to time. Following termination of the Account, the Company endeavours to erase and discard of Your data subject to the limitations and requirements under the applicable laws and regulations.<br className="calibre3" />&nbsp;</p>
							 <p className="block_6" >Limitations of Liability; Release; Indemnifications</p>
							 <p className="block_2" >THE SERVICES ARE PROVIDED ON 'AS IS' AND 'AS AVAILABLE' BASIS WITHOUT ANY REPRESENTATION OR WARRANTY, WHETHER EXPRESS, IMPLIED OR STATUTORY. THE COMPANY SPECIFICALLY DISCLAIMS ANY IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND/OR NON-INFRINGEMENT. THE COMPANY DOES NOT MAKE ANY REPRESENTATIONS OR WARRANTIES THAT YOUR ACCESS TO THE SITE, THE SERVICES, OR ANY PART OR MATERIALS MADE AVAILABLE THEREIN, WILL BE ERROR FREE, CONTINUOUS, UNINTERRUPTED OR ACCURATE.</p>
							 <p className="block_2" >IN NO EVENT WILL THE COMPANY, ITS SUBSIDIARIES, AFFILIATED PARTIES OR SERVICE PROVIDERS, OR ANY OF IT’S AND THEIR RESPECTIVE OFFICERS, DIRECTORS, AGENTS, JOINT VENTURERS, EMPLOYEES OR REPRESENTATIVES, BE LIABLE TO YOU OR ANYONE ON YOUR BEHALF, FOR ANY INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES, INCLUDING WITHOUT LIMITATIONS, LOSS OF REVENUES OR DATA, WHETHER BASED IN CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY, OR OTHERWISE, ARISING OUT OF OR IN CONNECTION WITH AUTHORIZED OR UNAUTHORIZED USE OF THE SITE OR SERVICES.&nbsp;</p>
							 <p className="block_2" >The Company specifically makes no warranties, representations or guarantees regarding the time required to complete processing any request provided by You, including electronic debit or credit using credit cards, bank accounts or checks, which are dependent upon many factors outside of the Company’s control. Without derogating from the aforementioned, the Company makes efforts to process Your requests in a timely manner.</p>
							 <p className="block_2"><b  className="calibre1">Release.&nbsp;</b><span >Any disputes between You and any other Member of the Site shall be exclusively resolved between You and such Member, and You release the Company, its affiliates and service providers, and each of their respective officers, directors, agents, joint ventures, employees and representatives from any and all claims, demands and damages (actual and consequential) of every kind and nature arising out of or in any way connected with such disputes.</span></p>
							 <p className="block_2"><b  className="calibre1">Indemnifications.</b><span >&nbsp;You agree to defend, protect, indemnify and hold harmless the Company, its subsidiaries and affiliates and each of its or their respective officers, directors, agents, joint ventures, employees and representatives from and against any and all claims, demands, costs, expenses, losses, liabilities and damages of every kind and nature (including, without limitation, reasonable attorneys’ fees) imposed upon or incurred by the Company directly or indirectly arising out of or related to (i) breach by You of the Terms of Use or other policies of the Company; or (ii) Your use of and access to the Site or the Services found at this Site; (iii) Your violation of any third-party right, including without limitation any intellectual property or other proprietary right; or (iv) any violation by You of any law, rule, regulation, or the rights of any third party. The indemnification obligations under this section shall survive any termination or expiration of the Terms of Use or the Member’s use of this Site or the Services found on this Site.</span></p>
							 <p className="block_8">&nbsp;</p>
							 <p className="block_6" >Modification and Termination of Services</p>
							 <p className="block_2" >The Company may suspend or terminate, with immediate effect, the operation of the Site or the provision of any part of the Services offered therein should such become illegal or subject to demand by any competent authority or is under any risk or exposure to any claims should it fail to do so, all subject to the Company’s sole discretion and You will have no complaints or demands with that respect.</p>
							 <p className="block_2" >In addition, although in principle the duration of this Site is undetermined, the Company reserves the right to modify, suspend or terminate the provision of any Service or content, in whole or in part, at any time and without notice to Members.</p>
							 <p className="block_2" >The Company may also change the Terms of Use of the Site or the Services offered at any time, including but not limited to:</p>
							 <ul className="list_1">
								<li className="block_5"><span >Change the prices without prior notice.</span></li>
								<li className="block_5"><span >Deny sale to Members accessing the services using anonymity tools, IP hiding and all those that hide identification and/or origin or fail to provide any documentations.</span></li>
								<li className="block_5"><span >Deny selling to Members who do not demonstrate minimum trust requirements, including without limitations, trust based in implementing algorithms on the data provided by the customers.</span></li>
								<li className="block_5"><span >Close the Site temporarily or permanently without notice.</span></li>
							 </ul>
							 <p className="block_2" >Your continual use of the Services following any amendment to the Terms of Use constitutes Your acceptance of such amendments.</p>
							 <p className="block_8">&nbsp;</p>
							 <p className="block_6" >Availability</p>
							 <p className="block_2" >All Services are provided without warranty of any kind, either express or implied. The Company does not represent that this Site will be available at all time to meet Your needs. The Company will strive to provide You with the Services as soon as practicably possible but there are no guarantees that access will not be interrupted, or that there will be no delays, failures, errors, omissions or loss of transmitted information.</p>
							 <p className="block_2" >The Company will use commercially reasonable endeavours to ensure that the Site is accessible by You in accordance with these Terms of Use. The Company may suspend use of the Site for maintenance and will make reasonable efforts to give You notice, however, You acknowledge that this may not be possible in any event of emergency.<br className="calibre3" />&nbsp;</p>
							 <p className="block_6" >External Websites</p>
							 <p className="block_2"><span >The Company makes no representations whatsoever about any other websites or services which You may access through this Site. The Site may present links or other forms of reference to other websites (the '</span><b  className="calibre1">External Websites</b><span >') or resources over which the Company has no control. You acknowledge that the Company may present such links or references to You only as a convenience and that the Company does not endorse any of the External Website services or offerings made to You or any content provided therein. The Company is not responsible for the availability of, and content provided on External Web Sites. </span></p>
							 <p className="block_2" >You are advised to review the policies posted by the External Website regarding privacy and other topics before use. The Company is not responsible for third party content accessible through the Site, including opinions, advice, statements, prices, activities, and advertisements, and You shall bear all risks associated with the use of such content. It is up to You to take precautions to ensure that whatever You select for Your use is free of such items as viruses, worms, Trojan horses and other items of a destructive nature.<br className="calibre3" />&nbsp;</p>
							 <p className="block_6" >No Advice</p>
							 <p className="block_2" >For the avoidance of doubt, the Company does not provide any financial, investment, legal, or any other advice in connection with the Services provided on the Site. </p>
							 <p className="block_2" >All Site Content is provided for informational purposes only.</p>
							 <p className="block_2" >The Company may provide information on the price, range, volatility of Virtual Currencies and events that have affected the price of the Virtual Currencies, but this is not considered investment or financial advice and should not be construed as such. Any decision to purchase or sell Virtual Currencies is Your exclusive decision carried out at Your own risk and the Company will not be liable for any loss suffered.</p>
							 <p className="block_2" ><br className="calibre3" />&nbsp;</p>
							 <p className="block_6" >General Provisions</p>
							 <p className="block_2"><b  className="calibre1">Entire Agreement.&nbsp;</b><span >These Terms of Use, the Privacy Policy, AML/KYC Policy, the Fee Schedule and the FAQs, are incorporated by reference herein and comprise the entire understanding and agreement between You and the Company as to the subject matter hereof, and supersedes any and all prior discussions, agreements and understandings of any kind (including without limitation any prior versions of this Agreement), and every nature between and among You and the Company.</span></p>
							 <p className="block_2" >Section headings in this Agreement are for convenience only, and shall not govern the meaning or interpretation of any provision of this Agreement.</p>
							 <p className="block_2"><b  className="calibre1">Relationship of the Parties.&nbsp;</b><span >Both You and the Company are independent contractors, and nothing in these Terms of Use shall be deemed to create between You and the Company any other form of relationship, and the parties shall not be deemed to be partners, joint ventures or agents. You are not authorized to make any obligations on behalf of the Company.</span></p>
							 <p className="block_2"><b  className="calibre1">Amendments.&nbsp;</b><span >The Company may amend or modify the Terms of Use by posting on the Company Site the revised Terms of Use, and the revised Terms of Use shall be effective at such time. If You do not agree with any such modification, Your sole and exclusive remedy is to terminate Your use of the Services and close Your Account. You agree that the Company shall not be liable to You or any third party for any modification or termination of the Services, or suspension or termination of Your access to the Services, except to the extent otherwise expressly set forth herein.</span></p>
							
							<p className="block_2">The Company shall notify You of any changed in these Terms of Use by posting a notification on the Site.</p>
							 
							 <p className="block_2"><b  className="calibre1">Assignment.&nbsp;</b><span >You may not assign any rights and/or licenses granted under these Terms of Use, the right to use the Account is exclusively Your for personal use. The Company reserves the right to assign our rights without restriction, including without limitation to any the Company affiliates or subsidiaries, or to any successor in interest of any business associated with the Services. Any attempted transfer or assignment in violation hereof shall be null and void. Subject to the foregoing, these Terms of Use will bind and inure to the benefit of the parties, their successors and permitted assigns.</span></p>
							 <p className="block_2"><b  className="calibre1">Severability.&nbsp;</b><span >If any provision of these Terms of Use shall be determined to be invalid or unenforceable under any rule, law or regulation or any governmental agency, local, state, or federal, such provision will be changed and interpreted to accomplish the objectives of the provision to the greatest extent possible under any applicable law and the validity or enforceability of any other provision of these Terms of Use shall not be affected.</span></p>
							 
							 <p className="block_2"><b  className="calibre1">Change of Control.&nbsp;</b><span >In the event that the Company is acquired by or merged with a third-party entity, the Company reserves the right, in any of these circumstances, to transfer or assign the information the Company has collected from You as part of such merger, acquisition, sale, or other change of control.</span></p>
							 <p className="block_2"><b  className="calibre1">Survival.&nbsp;</b><span >All provisions of these Terms of Use which by their nature extend beyond the expiration or termination of these Terms of Use, including, without limitation, sections pertaining to suspension or termination, the Company Account cancellation, debts owed to the Company, general use of the Site, disputes with the Company, and general provisions.</span></p>
							 <p className="block_2"><b  className="calibre1">Applicable Law and Dispute Resolution.&nbsp;</b><span >These Terms of Use will be governed by laws of Estonia. </span></p>
							 <p className="block_2" >Any dispute arising with respect to these Terms of Use shall be attempted to be resolved by the means of negotiations. If You and the Company would not reach the agreement within thirty (30) days of the beginning of such negotiations, the dispute will be exclusively submitted to confidential arbitrations by sole arbitrator agreed upon by the parties (and if not agreed upon, one will be appointed by the Court of Arbitration of the Estonian Chamber of Commerce and Industry) whose ruling will be provided within thirty (30) days and shall be deemed final and binding. The arbitration will be performed in the English language (unless otherwise agreed by the parties), and each party will be equally responsible for the costs of arbitration. The place and seat of Arbitration shall be Tallinn, Estonia.&nbsp;</p>
							 <p className="block_2"><b  className="calibre1">Force Majeure.&nbsp;</b><span >The Company shall not be liable for delays, failure in performance or interruption of service which results directly or indirectly from any cause or condition beyond its reasonable control, including, but not limited to, any delay or failure due to any act of God, act of civil or military authorities, act of terrorists, civil disturbance, war, strike or other labour dispute, fire, interruption in telecommunications or Internet services or network provider services, failure of equipment and/or software, malicious interferences with the Site, other catastrophe or any other occurrence which is beyond the Company’s reasonable control and shall not affect the validity and enforceability of any remaining provisions.</span></p>
							 
							 <p className="block_2"><b className="calibre1">English Language Prevails.&nbsp;</b><span >Notwithstanding any other provision of these Terms of Use, any translation of the Terms of Use, if provided, is provided for Your convenience. The meanings of terms, conditions and representations herein are subject to definitions and interpretations in the English language. Any translation provided may not accurately represent the information in the original English. In case of any inconstancies, English version of the Terms of Use shall prevail.<br className="calibre3" />&nbsp;</span></p>
							 <p className="block_6" >Contact Us</p>
							 <p className="block_3"><span className="text_">If You have any questions or feedbacks, You may contact the Company via the Company’s customer support at&nbsp;</span><span className="text_">. Please provide identifying information such as Your name, address, and any other information the Company may need to identify You, Your Account, and the transaction on which You have feedback or questions.</span></p>
						  </div>
					   </div>
					</div>
                { /* <div className={className}>{this.renderTermComp()}</div>*/ }
            </div>
        );
    }

    /*private renderTermComp = () => {
        const { loading } = this.props;
        //const { email } = this.state;

        return (
            <SignInComponent
                email={email}
            />
        );
    };*/
	
	 private translate = (key: string) => this.props.intl.formatMessage({id: key});

}

const mapStateToProps = (state: RootState): ReduxProps => ({
    colorTheme: selectCurrentColorTheme(state),
});

const mapDispatchToProps = dispatch => ({
    labelFetch: () => dispatch(labelFetch()),
});

// tslint:disable-next-line
export const PrivacyScreen = injectIntl(withRouter(connect(mapStateToProps, mapDispatchToProps)(Privacy) as any));
